/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.lexer;

import java.io.IOException;

public interface IPushbackReader {
	int read() throws IOException;
	
	void unread(int c) throws IOException;
}
