/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.lexer;

import nc.dssl.node.InvalidToken;

public class LexerException extends Exception {
	private final InvalidToken invalidToken;
	
	public LexerException(@SuppressWarnings("hiding") InvalidToken invalidToken, String message) {
		super(message);
		this.invalidToken = invalidToken;
	}
	
	public InvalidToken getToken() {
		return this.invalidToken;
	}
}
