/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.lexer;

import nc.dssl.node.*;

import java.io.*;

@SuppressWarnings("nls")
public class Lexer {
	protected Token token;
	protected State state = State.INITIAL;
	
	private final IPushbackReader in;
	private int line;
	private int pos;
	private boolean cr;
	private boolean eof;
	private final StringBuffer text = new StringBuffer();
	
	@SuppressWarnings("unused")
	protected void filter() throws LexerException, IOException {
		// Do nothing
	}
	
	public Lexer(@SuppressWarnings("hiding") final PushbackReader in) {
		this.in = new IPushbackReader() {
			
			private final PushbackReader pushbackReader = in;
			
			@Override
			public void unread(int c) throws IOException {
				pushbackReader.unread(c);
			}
			
			@Override
			public int read() throws IOException {
				return pushbackReader.read();
			}
		};
	}
	
	public Lexer(@SuppressWarnings("hiding") IPushbackReader in) {
		this.in = in;
	}
	
	public Token peek() throws LexerException, IOException {
		while (this.token == null) {
			this.token = getToken();
			filter();
		}
		
		return this.token;
	}
	
	public Token next() throws LexerException, IOException {
		while (this.token == null) {
			this.token = getToken();
			filter();
		}
		
		Token result = this.token;
		this.token = null;
		return result;
	}
	
	protected Token getToken() throws IOException, LexerException {
		int dfa_state = 0;
		
		int start_pos = this.pos;
		int start_line = this.line;
		
		int accept_state = -1;
		int accept_token = -1;
		int accept_length = -1;
		int accept_pos = -1;
		int accept_line = -1;
		
		@SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
		@SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
		this.text.setLength(0);
		
		while (true) {
			int c = getChar();
			
			if (c != -1) {
				switch (c) {
					case 10:
						if (this.cr) {
							this.cr = false;
						}
						else {
							this.line++;
							this.pos = 0;
						}
						break;
					case 13:
						this.line++;
						this.pos = 0;
						this.cr = true;
						break;
					default:
						this.pos++;
						this.cr = false;
						break;
				}
				
				this.text.append((char) c);
				
				do {
					int oldState = (dfa_state < -1) ? (-2 - dfa_state) : dfa_state;
					
					dfa_state = -1;
					
					int[][] tmp1 = gotoTable[oldState];
					int low = 0;
					int high = tmp1.length - 1;
					
					while (low <= high) {
						// int middle = (low + high) / 2;
						int middle = (low + high) >>> 1;
						int[] tmp2 = tmp1[middle];
						
						if (c < tmp2[0]) {
							high = middle - 1;
						}
						else if (c > tmp2[1]) {
							low = middle + 1;
						}
						else {
							dfa_state = tmp2[2];
							break;
						}
					}
				}
				while (dfa_state < -1);
			}
			else {
				dfa_state = -1;
			}
			
			if (dfa_state >= 0) {
				if (accept[dfa_state] != -1) {
					accept_state = dfa_state;
					accept_token = accept[dfa_state];
					accept_length = this.text.length();
					accept_pos = this.pos;
					accept_line = this.line;
				}
			}
			else {
				if (accept_state != -1) {
					switch (accept_token) {
						case 0: {
							@SuppressWarnings("hiding") Token token = new0(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 1: {
							@SuppressWarnings("hiding") Token token = new1(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 2: {
							@SuppressWarnings("hiding") Token token = new2(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 3: {
							@SuppressWarnings("hiding") Token token = new3(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 4: {
							@SuppressWarnings("hiding") Token token = new4(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 5: {
							@SuppressWarnings("hiding") Token token = new5(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 6: {
							@SuppressWarnings("hiding") Token token = new6(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 7: {
							@SuppressWarnings("hiding") Token token = new7(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 8: {
							@SuppressWarnings("hiding") Token token = new8(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 9: {
							@SuppressWarnings("hiding") Token token = new9(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 10: {
							@SuppressWarnings("hiding") Token token = new10(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 11: {
							@SuppressWarnings("hiding") Token token = new11(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 12: {
							@SuppressWarnings("hiding") Token token = new12(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 13: {
							@SuppressWarnings("hiding") Token token = new13(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 14: {
							@SuppressWarnings("hiding") Token token = new14(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 15: {
							@SuppressWarnings("hiding") Token token = new15(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 16: {
							@SuppressWarnings("hiding") Token token = new16(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 17: {
							@SuppressWarnings("hiding") Token token = new17(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 18: {
							@SuppressWarnings("hiding") Token token = new18(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 19: {
							@SuppressWarnings("hiding") Token token = new19(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 20: {
							@SuppressWarnings("hiding") Token token = new20(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 21: {
							@SuppressWarnings("hiding") Token token = new21(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 22: {
							@SuppressWarnings("hiding") Token token = new22(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 23: {
							@SuppressWarnings("hiding") Token token = new23(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 24: {
							@SuppressWarnings("hiding") Token token = new24(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 25: {
							@SuppressWarnings("hiding") Token token = new25(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 26: {
							@SuppressWarnings("hiding") Token token = new26(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 27: {
							@SuppressWarnings("hiding") Token token = new27(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 28: {
							@SuppressWarnings("hiding") Token token = new28(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 29: {
							@SuppressWarnings("hiding") Token token = new29(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 30: {
							@SuppressWarnings("hiding") Token token = new30(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 31: {
							@SuppressWarnings("hiding") Token token = new31(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 32: {
							@SuppressWarnings("hiding") Token token = new32(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 33: {
							@SuppressWarnings("hiding") Token token = new33(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 34: {
							@SuppressWarnings("hiding") Token token = new34(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 35: {
							@SuppressWarnings("hiding") Token token = new35(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 36: {
							@SuppressWarnings("hiding") Token token = new36(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 37: {
							@SuppressWarnings("hiding") Token token = new37(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 38: {
							@SuppressWarnings("hiding") Token token = new38(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 39: {
							@SuppressWarnings("hiding") Token token = new39(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 40: {
							@SuppressWarnings("hiding") Token token = new40(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 41: {
							@SuppressWarnings("hiding") Token token = new41(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 42: {
							@SuppressWarnings("hiding") Token token = new42(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 43: {
							@SuppressWarnings("hiding") Token token = new43(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 44: {
							@SuppressWarnings("hiding") Token token = new44(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 45: {
							@SuppressWarnings("hiding") Token token = new45(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 46: {
							@SuppressWarnings("hiding") Token token = new46(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 47: {
							@SuppressWarnings("hiding") Token token = new47(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 48: {
							@SuppressWarnings("hiding") Token token = new48(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 49: {
							@SuppressWarnings("hiding") Token token = new49(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 50: {
							@SuppressWarnings("hiding") Token token = new50(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 51: {
							@SuppressWarnings("hiding") Token token = new51(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 52: {
							@SuppressWarnings("hiding") Token token = new52(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 53: {
							@SuppressWarnings("hiding") Token token = new53(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 54: {
							@SuppressWarnings("hiding") Token token = new54(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 55: {
							@SuppressWarnings("hiding") Token token = new55(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 56: {
							@SuppressWarnings("hiding") Token token = new56(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 57: {
							@SuppressWarnings("hiding") Token token = new57(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 58: {
							@SuppressWarnings("hiding") Token token = new58(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 59: {
							@SuppressWarnings("hiding") Token token = new59(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 60: {
							@SuppressWarnings("hiding") Token token = new60(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 61: {
							@SuppressWarnings("hiding") Token token = new61(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 62: {
							@SuppressWarnings("hiding") Token token = new62(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 63: {
							@SuppressWarnings("hiding") Token token = new63(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 64: {
							@SuppressWarnings("hiding") Token token = new64(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 65: {
							@SuppressWarnings("hiding") Token token = new65(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 66: {
							@SuppressWarnings("hiding") Token token = new66(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 67: {
							@SuppressWarnings("hiding") Token token = new67(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 68: {
							@SuppressWarnings("hiding") Token token = new68(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 69: {
							@SuppressWarnings("hiding") Token token = new69(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 70: {
							@SuppressWarnings("hiding") Token token = new70(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 71: {
							@SuppressWarnings("hiding") Token token = new71(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 72: {
							@SuppressWarnings("hiding") Token token = new72(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 73: {
							@SuppressWarnings("hiding") Token token = new73(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 74: {
							@SuppressWarnings("hiding") Token token = new74(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 75: {
							@SuppressWarnings("hiding") Token token = new75(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 76: {
							@SuppressWarnings("hiding") Token token = new76(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 77: {
							@SuppressWarnings("hiding") Token token = new77(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 78: {
							@SuppressWarnings("hiding") Token token = new78(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 79: {
							@SuppressWarnings("hiding") Token token = new79(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 80: {
							@SuppressWarnings("hiding") Token token = new80(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 81: {
							@SuppressWarnings("hiding") Token token = new81(start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 82: {
							@SuppressWarnings("hiding") Token token = new82(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 83: {
							@SuppressWarnings("hiding") Token token = new83(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 84: {
							@SuppressWarnings("hiding") Token token = new84(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 85: {
							@SuppressWarnings("hiding") Token token = new85(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 86: {
							@SuppressWarnings("hiding") Token token = new86(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 87: {
							@SuppressWarnings("hiding") Token token = new87(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 88: {
							@SuppressWarnings("hiding") Token token = new88(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 89: {
							@SuppressWarnings("hiding") Token token = new89(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 90: {
							@SuppressWarnings("hiding") Token token = new90(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
						case 91: {
							@SuppressWarnings("hiding") Token token = new91(getText(accept_length), start_line + 1, start_pos + 1);
							pushBack(accept_length);
							this.pos = accept_pos;
							this.line = accept_line;
							return token;
						}
					}
				}
				else {
					int len = this.text.length();
					if (len > 0) {
						throw new LexerException(new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1), "[" + (start_line + 1) + "," + (start_pos + 1) + "]" + " Unknown token: " + this.text);
					}
					
					@SuppressWarnings("hiding") EOF token = new EOF(start_line + 1, start_pos + 1);
					return token;
				}
			}
		}
	}
	
	Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TBlank(text, line, pos);}
	
	Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TComment(text, line, pos);}
	
	Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLBrace(line, pos);}
	
	Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRBrace(line, pos);}
	
	Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRangeLBracket(line, pos);}
	
	Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRangeRBracket(line, pos);}
	
	Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TListLBracket(line, pos);}
	
	Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TListRBracket(line, pos);}
	
	Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TSetLBracket(line, pos);}
	
	Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TSetRBracket(line, pos);}
	
	Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDictLBracket(line, pos);}
	
	Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDictRBracket(line, pos);}
	
	Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TInclude(line, pos);}
	
	Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TImport(line, pos);}
	
	Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TNative(line, pos);}
	
	Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDef(line, pos);}
	
	Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMacro(line, pos);}
	
	Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TClass(line, pos);}
	
	Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDeref(line, pos);}
	
	Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDelete(line, pos);}
	
	Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TNew(line, pos);}
	
	Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TNull(line, pos);}
	
	Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TType(line, pos);}
	
	Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TCast(line, pos);}
	
	Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIs(line, pos);}
	
	Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TExch(line, pos);}
	
	Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRoll(line, pos);}
	
	Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPop(line, pos);}
	
	Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDup(line, pos);}
	
	Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TStacksize(line, pos);}
	
	Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TStackindex(line, pos);}
	
	Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRead(line, pos);}
	
	Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPrint(line, pos);}
	
	Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPrintln(line, pos);}
	
	Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TInterpret(line, pos);}
	
	Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TExec(line, pos);}
	
	Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIf(line, pos);}
	
	Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIfelse(line, pos);}
	
	Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLoop(line, pos);}
	
	Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRepeat(line, pos);}
	
	Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TForeach(line, pos);}
	
	Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TContinue(line, pos);}
	
	Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TBreak(line, pos);}
	
	Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TQuit(line, pos);}
	
	Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TEquals(line, pos);}
	
	Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIncrement(line, pos);}
	
	Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDecrement(line, pos);}
	
	Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPlusEquals(line, pos);}
	
	Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TAndEquals(line, pos);}
	
	Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TOrEquals(line, pos);}
	
	Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TXorEquals(line, pos);}
	
	Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMinusEquals(line, pos);}
	
	Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TConcatEquals(line, pos);}
	
	Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLeftShiftEquals(line, pos);}
	
	Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRightShiftEquals(line, pos);}
	
	Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMultiplyEquals(line, pos);}
	
	Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDivideEquals(line, pos);}
	
	Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRemainderEquals(line, pos);}
	
	Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPowerEquals(line, pos);}
	
	Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIdivideEquals(line, pos);}
	
	Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TModuloEquals(line, pos);}
	
	Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TEqualTo(line, pos);}
	
	Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TNotEqualTo(line, pos);}
	
	Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLessThan(line, pos);}
	
	Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLessOrEqual(line, pos);}
	
	Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMoreThan(line, pos);}
	
	Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMoreOrEqual(line, pos);}
	
	Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPlus(line, pos);}
	
	Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TAnd(line, pos);}
	
	Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TOr(line, pos);}
	
	Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TXor(line, pos);}
	
	Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMinus(line, pos);}
	
	Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TConcat(line, pos);}
	
	Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLeftShift(line, pos);}
	
	Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRightShift(line, pos);}
	
	Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMultiply(line, pos);}
	
	Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TDivide(line, pos);}
	
	Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TRemainder(line, pos);}
	
	Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TPower(line, pos);}
	
	Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIdivide(line, pos);}
	
	Token new80(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TModulo(line, pos);}
	
	Token new81(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TNot(line, pos);}
	
	Token new82(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIntValue(text, line, pos);}
	
	Token new83(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TBoolValue(text, line, pos);}
	
	Token new84(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TFloatValue(text, line, pos);}
	
	Token new85(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TCharValue(text, line, pos);}
	
	Token new86(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TBlockStringValue(text, line, pos);}
	
	Token new87(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLineStringValue(text, line, pos);}
	
	Token new88(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TIdentifier(text, line, pos);}
	
	Token new89(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TLabel(text, line, pos);}
	
	Token new90(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TMember(text, line, pos);}
	
	Token new91(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {return new TModule(text, line, pos);}
	
	private int getChar() throws IOException {
		if (this.eof) {
			return -1;
		}
		
		int result = this.in.read();
		
		if (result == -1) {
			this.eof = true;
		}
		
		return result;
	}
	
	private void pushBack(int acceptLength) throws IOException {
		int length = this.text.length();
		for (int i = length - 1; i >= acceptLength; i--) {
			this.eof = false;
			
			this.in.unread(this.text.charAt(i));
		}
	}
	
	protected void unread(@SuppressWarnings("hiding") Token token) throws IOException {
		@SuppressWarnings("hiding") String text = token.getText();
		int length = text.length();
		
		for (int i = length - 1; i >= 0; i--) {
			this.eof = false;
			
			this.in.unread(text.charAt(i));
		}
		
		this.pos = token.getPos() - 1;
		this.line = token.getLine() - 1;
	}
	
	private String getText(int acceptLength) {
		StringBuilder s = new StringBuilder(acceptLength);
		for (int i = 0; i < acceptLength; i++) {
			s.append(this.text.charAt(i));
		}
		
		return s.toString();
	}
	
	private static final int[][][][] gotoTable;
/*  {
		{ // INITIAL
			{{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {36, 36, 8}, {37, 37, 9}, {38, 38, 10}, {39, 39, 11}, {40, 40, 12}, {41, 41, 13}, {42, 42, 14}, {43, 43, 15}, {45, 45, 16}, {46, 46, 17}, {47, 47, 18}, {48, 57, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {91, 91, 24}, {93, 93, 25}, {94, 94, 26}, {95, 95, 23}, {97, 97, 23}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 23}, {105, 105, 32}, {106, 107, 23}, {108, 108, 33}, {109, 109, 34}, {110, 110, 35}, {111, 111, 23}, {112, 112, 36}, {113, 113, 37}, {114, 114, 38}, {115, 115, 39}, {116, 116, 40}, {117, 122, 23}, {123, 123, 41}, {124, 124, 42}, {125, 125, 43}, {126, 126, 44}, },
			{{9, 32, -2}, },
			{{9, 32, -2}, },
			{{9, 9, 1}, {10, 10, 45}, {13, 32, -2}, },
			{{9, 32, -2}, },
			{{61, 61, 46}, },
			{{0, 9, 47}, {11, 12, 47}, {14, 33, 47}, {34, 34, 48}, {35, 91, 47}, {92, 92, 49}, {93, 127, 47}, },
			{{0, 9, 50}, {10, 10, 51}, {11, 12, 50}, {13, 13, 52}, {14, 127, 50}, },
			{{65, 90, 53}, {95, 95, 53}, {97, 122, 53}, },
			{{37, 37, 54}, {61, 61, 55}, },
			{{61, 61, 56}, },
			{{0, 9, 57}, {11, 12, 57}, {14, 38, 57}, {40, 91, 57}, {92, 92, 58}, {93, 127, 57}, },
			{{124, 124, 59}, },
			{},
			{{42, 42, 60}, {61, 61, 61}, },
			{{43, 43, 62}, {46, 46, 63}, {48, 57, 19}, {61, 61, 64}, },
			{{45, 45, 65}, {46, 57, -17}, {61, 61, 66}, },
			{{48, 57, 67}, {65, 90, 68}, {95, 95, 68}, {97, 122, 68}, },
			{{42, 42, 69}, {47, 47, 70}, {61, 61, 71}, {65, 90, 72}, {95, 95, 72}, {97, 122, 72}, },
			{{46, 46, 73}, {48, 57, 19}, },
			{{60, 60, 74}, {61, 61, 75}, },
			{{61, 61, 76}, },
			{{61, 61, 77}, {62, 62, 78}, },
			{{48, 57, 79}, {65, 90, 80}, {95, 95, 80}, {97, 122, 80}, },
			{{124, 124, 81}, },
			{},
			{{61, 61, 82}, },
			{{48, 95, -25}, {97, 113, 80}, {114, 114, 83}, {115, 122, 80}, },
			{{48, 95, -25}, {97, 97, 84}, {98, 107, 80}, {108, 108, 85}, {109, 110, 80}, {111, 111, 86}, {112, 122, 80}, },
			{{48, 95, -25}, {97, 100, 80}, {101, 101, 87}, {102, 116, 80}, {117, 117, 88}, {118, 122, 80}, },
			{{48, 95, -25}, {97, 119, 80}, {120, 120, 89}, {121, 122, 80}, },
			{{48, 95, -25}, {97, 97, 90}, {98, 110, 80}, {111, 111, 91}, {112, 122, 80}, },
			{{48, 95, -25}, {97, 101, 80}, {102, 102, 92}, {103, 108, 80}, {109, 109, 93}, {110, 110, 94}, {111, 114, 80}, {115, 115, 95}, {116, 122, 80}, },
			{{48, 95, -25}, {97, 110, 80}, {111, 111, 96}, {112, 122, 80}, },
			{{48, 95, -25}, {97, 97, 97}, {98, 122, 80}, },
			{{48, 95, -25}, {97, 97, 98}, {98, 100, 80}, {101, 101, 99}, {102, 116, 80}, {117, 117, 100}, {118, 122, 80}, },
			{{48, 110, -35}, {111, 111, 101}, {112, 113, 80}, {114, 114, 102}, {115, 122, 80}, },
			{{48, 95, -25}, {97, 116, 80}, {117, 117, 103}, {118, 122, 80}, },
			{{34, 34, 6}, {48, 100, -31}, {101, 101, 104}, {102, 110, 80}, {111, 111, 105}, {112, 122, 80}, },
			{{48, 95, -25}, {97, 115, 80}, {116, 116, 106}, {117, 122, 80}, },
			{{48, 113, -29}, {114, 114, 107}, {115, 120, 80}, {121, 121, 108}, {122, 122, 80}, },
			{},
			{{41, 41, 109}, {61, 61, 110}, {93, 93, 111}, },
			{},
			{{61, 61, 112}, },
			{{9, 32, -2}, },
			{},
			{{0, 33, -8}, {34, 34, 113}, {35, 127, -8}, },
			{{34, 34, 114}, },
			{{0, 9, 115}, {11, 12, 115}, {14, 127, 115}, },
			{{0, 127, -9}, },
			{},
			{{10, 10, 116}, },
			{{48, 57, 117}, {65, 90, 118}, {95, 95, 118}, {97, 122, 118}, },
			{{61, 61, 119}, },
			{},
			{},
			{{39, 39, 120}, },
			{{0, 9, 121}, {11, 12, 121}, {14, 127, 121}, },
			{},
			{{61, 61, 122}, },
			{},
			{},
			{{48, 57, 67}, },
			{},
			{},
			{},
			{{48, 57, 67}, },
			{{48, 57, 123}, {65, 90, 124}, {95, 95, 124}, {97, 122, 124}, },
			{{0, 41, 125}, {42, 42, 126}, {43, 127, 125}, },
			{{61, 61, 127}, },
			{},
			{{48, 57, 128}, {65, 90, 129}, {95, 95, 129}, {97, 122, 129}, },
			{{48, 57, 130}, },
			{{61, 61, 131}, },
			{},
			{},
			{},
			{{61, 61, 132}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{},
			{},
			{{48, 100, -31}, {101, 101, 133}, {102, 122, 80}, },
			{{48, 95, -25}, {97, 114, 80}, {115, 115, 134}, {116, 122, 80}, },
			{{48, 95, -25}, {97, 97, 135}, {98, 122, 80}, },
			{{48, 95, -25}, {97, 109, 80}, {110, 110, 136}, {111, 122, 80}, },
			{{48, 101, -34}, {102, 102, 137}, {103, 107, 80}, {108, 108, 138}, {109, 113, 80}, {114, 114, 139}, {115, 122, 80}, },
			{{48, 95, -25}, {97, 111, 80}, {112, 112, 140}, {113, 122, 80}, },
			{{48, 95, -25}, {97, 98, 80}, {99, 99, 141}, {100, 100, 80}, {101, 101, 142}, {102, 122, 80}, },
			{{48, 95, -25}, {97, 107, 80}, {108, 108, 143}, {109, 122, 80}, },
			{{48, 113, -29}, {114, 114, 144}, {115, 122, 80}, },
			{{48, 100, -31}, {101, 101, 145}, {102, 122, 80}, },
			{{48, 111, -90}, {112, 112, 146}, {113, 122, 80}, },
			{{48, 98, -91}, {99, 99, 147}, {100, 115, 80}, {116, 116, 148}, {117, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 110, -35}, {111, 111, 149}, {112, 122, 80}, },
			{{48, 98, -91}, {99, 99, 150}, {100, 122, 80}, },
			{{48, 115, -41}, {116, 116, 151}, {117, 122, 80}, },
			{{48, 95, -25}, {97, 118, 80}, {119, 119, 152}, {120, 122, 80}, },
			{{48, 107, -92}, {108, 108, 153}, {109, 122, 80}, },
			{{48, 111, -90}, {112, 112, 154}, {113, 122, 80}, },
			{{48, 95, -25}, {97, 104, 80}, {105, 105, 155}, {106, 122, 80}, },
			{{48, 104, -104}, {105, 105, 156}, {106, 122, 80}, },
			{{48, 95, -25}, {97, 97, 157}, {98, 111, 80}, {112, 112, 158}, {113, 122, 80}, },
			{{48, 107, -92}, {108, 108, 159}, {109, 122, 80}, },
			{{48, 95, -25}, {97, 97, 160}, {98, 122, 80}, },
			{{48, 116, -39}, {117, 117, 161}, {118, 122, 80}, },
			{{48, 111, -90}, {112, 112, 162}, {113, 122, 80}, },
			{},
			{},
			{},
			{},
			{},
			{{9, 9, 163}, {10, 10, 164}, {13, 13, 165}, {32, 32, 166}, },
			{{0, 127, -49}, },
			{},
			{{48, 122, -55}, },
			{{48, 122, -55}, },
			{},
			{},
			{{39, 39, 120}, },
			{},
			{{48, 122, -70}, },
			{{48, 122, -70}, },
			{{0, 127, -71}, },
			{{0, 41, 167}, {42, 42, 126}, {43, 46, 167}, {47, 47, 168}, {48, 127, 167}, },
			{},
			{{48, 122, -74}, },
			{{48, 122, -74}, },
			{{48, 57, 130}, },
			{},
			{},
			{{48, 95, -25}, {97, 97, 169}, {98, 122, 80}, },
			{{48, 115, -41}, {116, 116, 170}, {117, 122, 80}, },
			{{48, 114, -86}, {115, 115, 171}, {116, 122, 80}, },
			{{48, 115, -41}, {116, 116, 172}, {117, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 100, -31}, {101, 101, 173}, {102, 122, 80}, },
			{{48, 100, -31}, {101, 101, 174}, {102, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 95, -25}, {97, 103, 80}, {104, 104, 175}, {105, 122, 80}, },
			{{48, 98, -91}, {99, 99, 176}, {100, 122, 80}, },
			{{48, 114, -86}, {115, 115, 177}, {116, 122, 80}, },
			{{48, 100, -31}, {101, 101, 178}, {102, 122, 80}, },
			{{48, 107, -92}, {108, 108, 179}, {109, 122, 80}, },
			{{48, 110, -35}, {111, 111, 180}, {112, 122, 80}, },
			{{48, 107, -92}, {108, 108, 181}, {109, 122, 80}, },
			{{48, 100, -31}, {101, 101, 182}, {102, 122, 80}, },
			{{48, 111, -90}, {112, 112, 183}, {113, 122, 80}, },
			{{48, 113, -29}, {114, 114, 184}, {115, 122, 80}, },
			{{48, 104, -104}, {105, 105, 185}, {106, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 107, -92}, {108, 108, 186}, {109, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 109, -88}, {110, 110, 187}, {111, 122, 80}, },
			{{48, 115, -41}, {116, 116, 188}, {117, 122, 80}, },
			{{48, 95, -25}, {97, 99, 80}, {100, 100, 189}, {101, 122, 80}, },
			{{48, 100, -31}, {101, 101, 190}, {102, 122, 80}, },
			{{48, 107, -92}, {108, 108, 191}, {109, 122, 80}, },
			{{48, 98, -91}, {99, 99, 192}, {100, 122, 80}, },
			{{48, 100, -31}, {101, 101, 193}, {102, 122, 80}, },
			{{48, 100, -31}, {101, 101, 194}, {102, 122, 80}, },
			{{9, 32, -116}, },
			{{0, 33, 195}, {34, 34, 196}, {35, 91, 195}, {92, 92, 197}, {93, 127, 195}, },
			{{0, 9, 195}, {10, 10, 198}, {11, 33, 195}, {34, 127, -166}, },
			{{9, 32, -116}, },
			{{0, 41, 199}, {42, 42, 200}, {43, 127, 199}, },
			{},
			{{48, 95, -25}, {97, 106, 80}, {107, 107, 201}, {108, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 114, -86}, {115, 115, 202}, {116, 122, 80}, },
			{{48, 104, -104}, {105, 105, 203}, {106, 122, 80}, },
			{{48, 115, -41}, {116, 116, 204}, {117, 122, 80}, },
			{{48, 101, -34}, {102, 102, 205}, {103, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 100, -31}, {101, 101, 206}, {102, 122, 80}, },
			{{48, 95, -25}, {97, 97, 207}, {98, 122, 80}, },
			{{48, 114, -86}, {115, 115, 208}, {116, 122, 80}, },
			{{48, 113, -29}, {114, 114, 209}, {115, 122, 80}, },
			{{48, 116, -39}, {117, 117, 210}, {118, 122, 80}, },
			{{48, 113, -29}, {114, 114, 211}, {115, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 110, -35}, {111, 111, 212}, {112, 122, 80}, },
			{{48, 95, -25}, {97, 117, 80}, {118, 118, 213}, {119, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 115, -41}, {116, 116, 214}, {117, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 95, -25}, {97, 97, 215}, {98, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 106, -171}, {107, 107, 216}, {108, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{0, 127, -166}, },
			{{34, 34, 217}, },
			{{0, 9, 218}, {11, 12, 218}, {14, 127, 218}, },
			{{0, 127, -166}, },
			{{0, 127, -169}, },
			{{0, 41, 167}, {42, 42, 200}, {43, 127, -128}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 109, -88}, {110, 110, 219}, {111, 122, 80}, },
			{{48, 100, -31}, {101, 101, 220}, {102, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 98, -91}, {99, 99, 221}, {100, 122, 80}, },
			{{48, 100, -31}, {101, 101, 222}, {102, 122, 80}, },
			{{48, 115, -41}, {116, 116, 223}, {117, 122, 80}, },
			{{48, 99, -159}, {100, 100, 224}, {101, 122, 80}, },
			{{48, 111, -90}, {112, 112, 225}, {113, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 100, -31}, {101, 101, 226}, {102, 122, 80}, },
			{{48, 107, -92}, {108, 108, 227}, {109, 122, 80}, },
			{{48, 115, -41}, {116, 116, 228}, {117, 122, 80}, },
			{{48, 104, -104}, {105, 105, 229}, {106, 114, 80}, {115, 115, 230}, {116, 122, 80}, },
			{{34, 34, 231}, },
			{{0, 127, -166}, },
			{{48, 116, -39}, {117, 117, 232}, {118, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 103, -143}, {104, 104, 233}, {105, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 100, -31}, {101, 101, 234}, {102, 122, 80}, },
			{{48, 113, -29}, {114, 114, 235}, {115, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 109, -88}, {110, 110, 236}, {111, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 109, -88}, {110, 110, 237}, {111, 122, 80}, },
			{{48, 104, -104}, {105, 105, 238}, {106, 122, 80}, },
			{},
			{{48, 100, -31}, {101, 101, 239}, {102, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
			{{48, 100, -31}, {101, 101, 240}, {102, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 99, -159}, {100, 100, 241}, {101, 122, 80}, },
			{{48, 95, -25}, {97, 121, 80}, {122, 122, 242}, },
			{{48, 122, -25}, },
			{{48, 115, -41}, {116, 116, 243}, {117, 122, 80}, },
			{{48, 100, -31}, {101, 101, 244}, {102, 122, 80}, },
			{{48, 100, -31}, {101, 101, 245}, {102, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 119, -32}, {120, 120, 246}, {121, 122, 80}, },
			{{48, 122, -25}, },
			{{48, 122, -25}, },
		}
	};*/
	
	private static final int[][] accept;
/*  {
		// INITIAL
		{-1, 0, 0, 0, 0, 81, -1, 1, -1, 77, 68, -1, 4, 5, 75, 67, 71, -1, 76, 82, 63, 44, 65, 88, 6, 7, 70, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 2, 69, 3, 72, 0, 62, -1, 87, -1, 1, 1, 1, 91, 80, 57, 48, -1, -1, 8, 78, 55, 45, -1, 47, 46, 51, 84, 90, -1, 79, 56, 89, 84, 73, 64, 61, 66, 74, 88, 88, 10, 50, 88, 88, 88, 88, 88, 88, 88, 88, 88, 36, 88, 88, 24, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 9, 49, 11, 52, 87, -1, -1, 1, 91, 91, 60, 85, -1, 58, 90, 90, -1, -1, 59, 89, 89, 84, 53, 54, 88, 88, 88, 88, 15, 88, 88, 28, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 20, 88, 27, 88, 88, 88, 88, 88, 88, 88, 88, -1, -1, -1, -1, -1, 1, 88, 23, 88, 88, 88, 88, 25, 35, 88, 88, 88, 88, 88, 88, 38, 88, 88, 21, 88, 43, 31, 88, 26, 88, 83, 22, -1, -1, -1, -1, -1, -1, 42, 17, 88, 88, 18, 83, 88, 88, 88, 88, 88, 16, 88, 32, 88, 88, -1, -1, 88, 19, 88, 37, 13, 88, 88, 14, 88, 39, 88, 88, 86, 88, 40, 12, 88, 33, 88, 88, 41, 88, 88, 88, 34, 88, 29, 30, },

	};*/
	
	public static class State {
		public final static State INITIAL = new State(0);
		
		private final int id;
		
		private State(@SuppressWarnings("hiding") int id) {
			this.id = id;
		}
		
		public int id() {
			return this.id;
		}
	}
	
	static {
		try {
			DataInputStream s = new DataInputStream(new BufferedInputStream(Lexer.class.getResourceAsStream("lexer.dat")));
			
			// read gotoTable
			int length = s.readInt();
			gotoTable = new int[length][][][];
			for (int i = 0; i < gotoTable.length; i++) {
				length = s.readInt();
				gotoTable[i] = new int[length][][];
				for (int j = 0; j < gotoTable[i].length; j++) {
					length = s.readInt();
					gotoTable[i][j] = new int[length][3];
					for (int k = 0; k < gotoTable[i][j].length; k++) {
						for (int l = 0; l < 3; l++) {
							gotoTable[i][j][k][l] = s.readInt();
						}
					}
				}
			}
			
			length = s.readInt();
			accept = new int[length][];
			for (int i = 0; i < accept.length; i++) {
				length = s.readInt();
				accept[i] = new int[length];
				for (int j = 0; j < accept[i].length; j++) {
					accept[i][j] = s.readInt();
				}
			}
			
			s.close();
		}
		catch (Exception e) {
			throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
		}
	}
}
