/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class EOF extends Token {
	public EOF() {
		setText("");
	}
	
	public EOF(int line, int pos) {
		setText("");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new EOF(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseEOF(this);
	}
}
