/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDef extends Token {
	public TDef() {
		super.setText("def");
	}
	
	public TDef(int line, int pos) {
		super.setText("def");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDef(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDef(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDef text.");
	}
}
