/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDeref extends Token {
	public TDeref() {
		super.setText("deref");
	}
	
	public TDeref(int line, int pos) {
		super.setText("deref");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDeref(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDeref(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDeref text.");
	}
}
