/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDictLBracket extends Token {
	public TDictLBracket() {
		super.setText("[|");
	}
	
	public TDictLBracket(int line, int pos) {
		super.setText("[|");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDictLBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDictLBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDictLBracket text.");
	}
}
