/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDictRBracket extends Token {
	public TDictRBracket() {
		super.setText("|]");
	}
	
	public TDictRBracket(int line, int pos) {
		super.setText("|]");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDictRBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDictRBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDictRBracket text.");
	}
}
