/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDivideEquals extends Token {
	public TDivideEquals() {
		super.setText("/=");
	}
	
	public TDivideEquals(int line, int pos) {
		super.setText("/=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDivideEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDivideEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDivideEquals text.");
	}
}
