/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDup extends Token {
	public TDup() {
		super.setText("dup");
	}
	
	public TDup(int line, int pos) {
		super.setText("dup");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TDup(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTDup(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TDup text.");
	}
}
