/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TIdivideEquals extends Token {
	public TIdivideEquals() {
		super.setText("//=");
	}
	
	public TIdivideEquals(int line, int pos) {
		super.setText("//=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TIdivideEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTIdivideEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TIdivideEquals text.");
	}
}
