/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLeftShift extends Token {
	public TLeftShift() {
		super.setText("<<");
	}
	
	public TLeftShift(int line, int pos) {
		super.setText("<<");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TLeftShift(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTLeftShift(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TLeftShift text.");
	}
}
