/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLessThan extends Token {
	public TLessThan() {
		super.setText("<");
	}
	
	public TLessThan(int line, int pos) {
		super.setText("<");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TLessThan(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTLessThan(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TLessThan text.");
	}
}
