/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLessOrEqual extends Token {
	public TLessOrEqual() {
		super.setText("<=");
	}
	
	public TLessOrEqual(int line, int pos) {
		super.setText("<=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TLessOrEqual(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTLessOrEqual(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TLessOrEqual text.");
	}
}
