/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLineStringValue extends Token {
	public TLineStringValue(String text) {
		setText(text);
	}
	
	public TLineStringValue(String text, int line, int pos) {
		setText(text);
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TLineStringValue(getText(), getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTLineStringValue(this);
	}
}
