/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TListLBracket extends Token {
	public TListLBracket() {
		super.setText("[");
	}
	
	public TListLBracket(int line, int pos) {
		super.setText("[");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TListLBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTListLBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TListLBracket text.");
	}
}
