/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TListRBracket extends Token {
	public TListRBracket() {
		super.setText("]");
	}
	
	public TListRBracket(int line, int pos) {
		super.setText("]");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TListRBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTListRBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TListRBracket text.");
	}
}
