/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TMinusEquals extends Token {
	public TMinusEquals() {
		super.setText("-=");
	}
	
	public TMinusEquals(int line, int pos) {
		super.setText("-=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TMinusEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTMinusEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TMinusEquals text.");
	}
}
