/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TModule extends Token {
	public TModule(String text) {
		setText(text);
	}
	
	public TModule(String text, int line, int pos) {
		setText(text);
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TModule(getText(), getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTModule(this);
	}
}
