/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TModuloEquals extends Token {
	public TModuloEquals() {
		super.setText("%%=");
	}
	
	public TModuloEquals(int line, int pos) {
		super.setText("%%=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TModuloEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTModuloEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TModuloEquals text.");
	}
}
