/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TMultiply extends Token {
	public TMultiply() {
		super.setText("*");
	}
	
	public TMultiply(int line, int pos) {
		super.setText("*");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TMultiply(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTMultiply(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TMultiply text.");
	}
}
