/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TNotEqualTo extends Token {
	public TNotEqualTo() {
		super.setText("!=");
	}
	
	public TNotEqualTo(int line, int pos) {
		super.setText("!=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TNotEqualTo(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTNotEqualTo(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TNotEqualTo text.");
	}
}
