/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TPlusEquals extends Token {
	public TPlusEquals() {
		super.setText("+=");
	}
	
	public TPlusEquals(int line, int pos) {
		super.setText("+=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TPlusEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTPlusEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TPlusEquals text.");
	}
}
