/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TPop extends Token {
	public TPop() {
		super.setText("pop");
	}
	
	public TPop(int line, int pos) {
		super.setText("pop");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TPop(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTPop(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TPop text.");
	}
}
