/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TPowerEquals extends Token {
	public TPowerEquals() {
		super.setText("**=");
	}
	
	public TPowerEquals(int line, int pos) {
		super.setText("**=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TPowerEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTPowerEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TPowerEquals text.");
	}
}
