/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TPrintln extends Token {
	public TPrintln() {
		super.setText("println");
	}
	
	public TPrintln(int line, int pos) {
		super.setText("println");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TPrintln(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTPrintln(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TPrintln text.");
	}
}
