/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TRangeRBracket extends Token {
	public TRangeRBracket() {
		super.setText(")");
	}
	
	public TRangeRBracket(int line, int pos) {
		super.setText(")");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TRangeRBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTRangeRBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TRangeRBracket text.");
	}
}
