/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TRangeLBracket extends Token {
	public TRangeLBracket() {
		super.setText("(");
	}
	
	public TRangeLBracket(int line, int pos) {
		super.setText("(");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TRangeLBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTRangeLBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TRangeLBracket text.");
	}
}
