/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TRightShift extends Token {
	public TRightShift() {
		super.setText(">>");
	}
	
	public TRightShift(int line, int pos) {
		super.setText(">>");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TRightShift(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTRightShift(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TRightShift text.");
	}
}
