/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TSetRBracket extends Token {
	public TSetRBracket() {
		super.setText("|)");
	}
	
	public TSetRBracket(int line, int pos) {
		super.setText("|)");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TSetRBracket(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTSetRBracket(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TSetRBracket text.");
	}
}
