/* This file was generated by SableCC (http://www.sablecc.org/). */

package nc.dssl.node;

import nc.dssl.analysis.Analysis;

@SuppressWarnings("nls")
public final class TXorEquals extends Token {
	public TXorEquals() {
		super.setText("^=");
	}
	
	public TXorEquals(int line, int pos) {
		super.setText("^=");
		setLine(line);
		setPos(pos);
	}
	
	@Override
	public Object clone() {
		return new TXorEquals(getLine(), getPos());
	}
	
	@Override
	public void apply(Switch sw) {
		((Analysis) sw).caseTXorEquals(this);
	}
	
	@Override
	public void setText(@SuppressWarnings("unused") String text) {
		throw new RuntimeException("Cannot change TXorEquals text.");
	}
}
