package nc.tile.multiblock;

public enum MultiblockType {
	
	SOLID_FUEL_FISSION_FACE, SOLID_FUEL_FISSION_EDGE,
	TOKOMAK_FUSION_CORE, TOKOMAK_FUSION_RING, TOKOMAK_FUSION_BLANKET, TOKOMAK_FUSION_CONNECTOR,
	ACCELERATOR_RING, ACCELERATOR_COOLING;
}
