package nc.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelNuclearWorkspace extends ModelBase
{
  //fields
    ModelRenderer workspacetop1;
    ModelRenderer leg1a;
    ModelRenderer leg1b;
    ModelRenderer leg1c;
    ModelRenderer leg1d;
    ModelRenderer leg2a;
    ModelRenderer leg2b;
    ModelRenderer leg2c;
    ModelRenderer leg2d;
    ModelRenderer leg3a;
    ModelRenderer leg3b;
    ModelRenderer leg3c;
    ModelRenderer leg3d;
    ModelRenderer leg4a;
    ModelRenderer leg4b;
    ModelRenderer leg4c;
    ModelRenderer leg4d;
    ModelRenderer leg5a;
    ModelRenderer leg5b;
    ModelRenderer leg5c;
    ModelRenderer leg5d;
    ModelRenderer leg6a;
    ModelRenderer leg6b;
    ModelRenderer leg6c;
    ModelRenderer leg6d;
    ModelRenderer workspacetop2;
    ModelRenderer workspacetop3;
    ModelRenderer workspacetop4;
    ModelRenderer workspacetop5;
    ModelRenderer workspacetop6;
    ModelRenderer leg7a;
    ModelRenderer leg7b;
    ModelRenderer leg7c;
    ModelRenderer leg7d;
  
  public ModelNuclearWorkspace()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      workspacetop1 = new ModelRenderer(this, 0, 0);
      workspacetop1.addBox(0F, 0F, 0F, 16, 1, 16);
      workspacetop1.setRotationPoint(-8F, 12F, -8F);
      workspacetop1.setTextureSize(128, 128);
      workspacetop1.mirror = true;
      setRotation(workspacetop1, 0F, 0F, 0F);
      leg1a = new ModelRenderer(this, 0, 17);
      leg1a.addBox(0F, 0F, 0F, 7, 1, 7);
      leg1a.setRotationPoint(-8F, 23F, -8F);
      leg1a.setTextureSize(128, 128);
      leg1a.mirror = true;
      setRotation(leg1a, 0F, 0F, 0F);
      leg1b = new ModelRenderer(this, 28, 17);
      leg1b.addBox(0F, 0F, 0F, 7, 1, 7);
      leg1b.setRotationPoint(1F, 23F, 1F);
      leg1b.setTextureSize(128, 128);
      leg1b.mirror = true;
      setRotation(leg1b, 0F, 0F, 0F);
      leg1c = new ModelRenderer(this, 0, 25);
      leg1c.addBox(0F, 0F, 0F, 7, 1, 7);
      leg1c.setRotationPoint(-8F, 23F, 1F);
      leg1c.setTextureSize(128, 128);
      leg1c.mirror = true;
      setRotation(leg1c, 0F, 0F, 0F);
      leg1d = new ModelRenderer(this, 28, 25);
      leg1d.addBox(0F, 0F, 0F, 7, 1, 7);
      leg1d.setRotationPoint(1F, 23F, -8F);
      leg1d.setTextureSize(128, 128);
      leg1d.mirror = true;
      setRotation(leg1d, 0F, 0F, 0F);
      leg2a = new ModelRenderer(this, 24, 33);
      leg2a.addBox(0F, 0F, 0F, 6, 1, 6);
      leg2a.setRotationPoint(-7F, 22F, 1F);
      leg2a.setTextureSize(128, 128);
      leg2a.mirror = true;
      setRotation(leg2a, 0F, 0F, 0F);
      leg2b = new ModelRenderer(this, 0, 33);
      leg2b.addBox(0F, 0F, 0F, 6, 1, 6);
      leg2b.setRotationPoint(1F, 22F, 1F);
      leg2b.setTextureSize(128, 128);
      leg2b.mirror = true;
      setRotation(leg2b, 0F, 0F, 0F);
      leg2c = new ModelRenderer(this, 0, 40);
      leg2c.addBox(0F, 0F, 0F, 6, 1, 6);
      leg2c.setRotationPoint(1F, 22F, -7F);
      leg2c.setTextureSize(128, 128);
      leg2c.mirror = true;
      setRotation(leg2c, 0F, 0F, 0F);
      leg2d = new ModelRenderer(this, 24, 40);
      leg2d.addBox(0F, 0F, 0F, 6, 1, 6);
      leg2d.setRotationPoint(-7F, 22F, -7F);
      leg2d.setTextureSize(128, 128);
      leg2d.mirror = true;
      setRotation(leg2d, 0F, 0F, 0F);
      leg3a = new ModelRenderer(this, 0, 47);
      leg3a.addBox(0F, 0F, 0F, 5, 1, 5);
      leg3a.setRotationPoint(1F, 21F, 1F);
      leg3a.setTextureSize(128, 128);
      leg3a.mirror = true;
      setRotation(leg3a, 0F, 0F, 0F);
      leg3b = new ModelRenderer(this, 20, 47);
      leg3b.addBox(0F, 0F, 0F, 5, 1, 5);
      leg3b.setRotationPoint(-6F, 21F, 1F);
      leg3b.setTextureSize(128, 128);
      leg3b.mirror = true;
      setRotation(leg3b, 0F, 0F, 0F);
      leg3c = new ModelRenderer(this, 0, 53);
      leg3c.addBox(0F, 0F, 0F, 5, 1, 5);
      leg3c.setRotationPoint(1F, 21F, -6F);
      leg3c.setTextureSize(128, 128);
      leg3c.mirror = true;
      setRotation(leg3c, 0F, 0F, 0F);
      leg3d = new ModelRenderer(this, 20, 53);
      leg3d.addBox(0F, 0F, 0F, 5, 1, 5);
      leg3d.setRotationPoint(-6F, 21F, -6F);
      leg3d.setTextureSize(128, 128);
      leg3d.mirror = true;
      setRotation(leg3d, 0F, 0F, 0F);
      leg4a = new ModelRenderer(this, 0, 59);
      leg4a.addBox(0F, 0F, 0F, 4, 1, 4);
      leg4a.setRotationPoint(1F, 20F, 1F);
      leg4a.setTextureSize(128, 128);
      leg4a.mirror = true;
      setRotation(leg4a, 0F, 0F, 0F);
      leg4b = new ModelRenderer(this, 16, 59);
      leg4b.addBox(0F, 0F, 0F, 4, 1, 4);
      leg4b.setRotationPoint(-5F, 20F, 1F);
      leg4b.setTextureSize(128, 128);
      leg4b.mirror = true;
      setRotation(leg4b, 0F, 0F, 0F);
      leg4c = new ModelRenderer(this, 0, 64);
      leg4c.addBox(0F, 0F, 0F, 4, 1, 4);
      leg4c.setRotationPoint(-5F, 20F, -5F);
      leg4c.setTextureSize(128, 128);
      leg4c.mirror = true;
      setRotation(leg4c, 0F, 0F, 0F);
      leg4d = new ModelRenderer(this, 16, 64);
      leg4d.addBox(0F, 0F, 0F, 4, 1, 4);
      leg4d.setRotationPoint(1F, 20F, -5F);
      leg4d.setTextureSize(128, 128);
      leg4d.mirror = true;
      setRotation(leg4d, 0F, 0F, 0F);
      leg5a = new ModelRenderer(this, 0, 69);
      leg5a.addBox(0F, 0F, 0F, 3, 1, 3);
      leg5a.setRotationPoint(-4F, 19F, 1F);
      leg5a.setTextureSize(128, 128);
      leg5a.mirror = true;
      setRotation(leg5a, 0F, 0F, 0F);
      leg5b = new ModelRenderer(this, 12, 69);
      leg5b.addBox(0F, 0F, 0F, 3, 1, 3);
      leg5b.setRotationPoint(1F, 19F, 1F);
      leg5b.setTextureSize(128, 128);
      leg5b.mirror = true;
      setRotation(leg5b, 0F, 0F, 0F);
      leg5c = new ModelRenderer(this, 0, 73);
      leg5c.addBox(0F, 0F, 0F, 3, 1, 3);
      leg5c.setRotationPoint(-4F, 19F, -4F);
      leg5c.setTextureSize(128, 128);
      leg5c.mirror = true;
      setRotation(leg5c, 0F, 0F, 0F);
      leg5d = new ModelRenderer(this, 12, 73);
      leg5d.addBox(0F, 0F, 0F, 3, 1, 3);
      leg5d.setRotationPoint(1F, 19F, -4F);
      leg5d.setTextureSize(128, 128);
      leg5d.mirror = true;
      setRotation(leg5d, 0F, 0F, 0F);
      leg6a = new ModelRenderer(this, 0, 77);
      leg6a.addBox(0F, 0F, 0F, 2, 1, 2);
      leg6a.setRotationPoint(1F, 18F, 1F);
      leg6a.setTextureSize(128, 128);
      leg6a.mirror = true;
      setRotation(leg6a, 0F, 0F, 0F);
      leg6b = new ModelRenderer(this, 8, 77);
      leg6b.addBox(0F, 0F, 0F, 2, 1, 2);
      leg6b.setRotationPoint(-3F, 18F, 1F);
      leg6b.setTextureSize(128, 128);
      leg6b.mirror = true;
      setRotation(leg6b, 0F, 0F, 0F);
      leg6c = new ModelRenderer(this, 0, 80);
      leg6c.addBox(0F, 0F, 0F, 2, 1, 2);
      leg6c.setRotationPoint(1F, 18F, -3F);
      leg6c.setTextureSize(128, 128);
      leg6c.mirror = true;
      setRotation(leg6c, 0F, 0F, 0F);
      leg6d = new ModelRenderer(this, 8, 80);
      leg6d.addBox(0F, 0F, 0F, 2, 1, 2);
      leg6d.setRotationPoint(-3F, 18F, -3F);
      leg6d.setTextureSize(128, 128);
      leg6d.mirror = true;
      setRotation(leg6d, 0F, 0F, 0F);
      workspacetop2 = new ModelRenderer(this, 64, 0);
      workspacetop2.addBox(0F, 0F, 0F, 14, 1, 14);
      workspacetop2.setRotationPoint(-7F, 13F, -7F);
      workspacetop2.setTextureSize(128, 128);
      workspacetop2.mirror = true;
      setRotation(workspacetop2, 0F, 0F, 0F);
      workspacetop3 = new ModelRenderer(this, 64, 15);
      workspacetop3.addBox(0F, 0F, 0F, 12, 1, 12);
      workspacetop3.setRotationPoint(-6F, 14F, -6F);
      workspacetop3.setTextureSize(128, 128);
      workspacetop3.mirror = true;
      setRotation(workspacetop3, 0F, 0F, 0F);
      workspacetop4 = new ModelRenderer(this, 64, 28);
      workspacetop4.addBox(0F, 0F, 0F, 10, 1, 10);
      workspacetop4.setRotationPoint(-5F, 15F, -5F);
      workspacetop4.setTextureSize(128, 128);
      workspacetop4.mirror = true;
      setRotation(workspacetop4, 0F, 0F, 0F);
      workspacetop5 = new ModelRenderer(this, 64, 39);
      workspacetop5.addBox(0F, 0F, 0F, 8, 1, 8);
      workspacetop5.setRotationPoint(-4F, 16F, -4F);
      workspacetop5.setTextureSize(128, 128);
      workspacetop5.mirror = true;
      setRotation(workspacetop5, 0F, 0F, 0F);
      workspacetop6 = new ModelRenderer(this, 64, 48);
      workspacetop6.addBox(0F, 0F, 0F, 6, 1, 6);
      workspacetop6.setRotationPoint(-3F, 17F, -3F);
      workspacetop6.setTextureSize(128, 128);
      workspacetop6.mirror = true;
      setRotation(workspacetop6, 0F, 0F, 0F);
      leg7a = new ModelRenderer(this, 64, 55);
      leg7a.addBox(0F, 0F, 0F, 1, 8, 1);
      leg7a.setRotationPoint(-7F, 14F, -7F);
      leg7a.setTextureSize(128, 128);
      leg7a.mirror = true;
      setRotation(leg7a, 0F, 0F, 0F);
      leg7b = new ModelRenderer(this, 68, 55);
      leg7b.addBox(0F, 0F, 0F, 1, 8, 1);
      leg7b.setRotationPoint(6F, 14F, 6F);
      leg7b.setTextureSize(128, 128);
      leg7b.mirror = true;
      setRotation(leg7b, 0F, 0F, 0F);
      leg7c = new ModelRenderer(this, 72, 55);
      leg7c.addBox(0F, 0F, 0F, 1, 8, 1);
      leg7c.setRotationPoint(6F, 14F, -7F);
      leg7c.setTextureSize(128, 128);
      leg7c.mirror = true;
      setRotation(leg7c, 0F, 0F, 0F);
      leg7d = new ModelRenderer(this, 76, 55);
      leg7d.addBox(0F, 0F, 0F, 1, 8, 1);
      leg7d.setRotationPoint(-7F, 14F, 6F);
      leg7d.setTextureSize(128, 128);
      leg7d.mirror = true;
      setRotation(leg7d, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    workspacetop1.render(f5);
    leg1a.render(f5);
    leg1b.render(f5);
    leg1c.render(f5);
    leg1d.render(f5);
    leg2a.render(f5);
    leg2b.render(f5);
    leg2c.render(f5);
    leg2d.render(f5);
    leg3a.render(f5);
    leg3b.render(f5);
    leg3c.render(f5);
    leg3d.render(f5);
    leg4a.render(f5);
    leg4b.render(f5);
    leg4c.render(f5);
    leg4d.render(f5);
    leg5a.render(f5);
    leg5b.render(f5);
    leg5c.render(f5);
    leg5d.render(f5);
    leg6a.render(f5);
    leg6b.render(f5);
    leg6c.render(f5);
    leg6d.render(f5);
    workspacetop2.render(f5);
    workspacetop3.render(f5);
    workspacetop4.render(f5);
    workspacetop5.render(f5);
    workspacetop6.render(f5);
    leg7a.render(f5);
    leg7b.render(f5);
    leg7c.render(f5);
    leg7d.render(f5);
  }
  
  public void renderModel(float f) {
	  workspacetop1.render(f);
	  leg1a.render(f);
	  leg1b.render(f);
	  leg1c.render(f);
	  leg1d.render(f);
	  leg2a.render(f);
      leg2b.render(f);
	  leg2c.render(f);
      leg2d.render(f);
      leg3a.render(f);
	  leg3b.render(f);
	  leg3c.render(f);
	  leg3d.render(f);
	  leg4a.render(f);
	  leg4b.render(f);
	  leg4c.render(f);
	  leg4d.render(f);
	  leg5a.render(f);
	  leg5b.render(f);
	  leg5c.render(f);
	  leg5d.render(f);
	  leg6a.render(f);
	  leg6b.render(f);
	  leg6c.render(f);
	  leg6d.render(f);
	  workspacetop2.render(f);
	  workspacetop3.render(f);
	  workspacetop4.render(f);
	  workspacetop5.render(f);
	  workspacetop6.render(f);
	  leg7a.render(f);
	  leg7b.render(f);
	  leg7c.render(f);
	  leg7d.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
